name: app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0-169.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  hexcolor: ^2.0.4
  flutter_bloc: ^8.1.1
  firebase_core: ^1.3.0
  firebase_auth: ^3.1.1
  cloud_firestore: ^3.5.1
  provider: ^6.0.0
  bloc_test: ^9.1.0
  image_picker: ^0.8.1+3
  firebase_storage: ^10.0.3
  rxdart: ^0.27.1
  syncfusion_flutter_charts: ^20.2.44
  cached_network_image: ^3.1.0
  mocktail: ^0.3.0
  equatable: ^2.0.3
  cupertino_icons: ^1.0.5
  shared_preferences: ^2.0.15
  material_design_icons_flutter: ^5.0.6996
  sqflite: ^2.0.3+1
  path: ^1.8.1
  internet_connection_checker: ^0.0.1+4
  flutter_launcher_icons: ^0.10.0

dev_dependencies:
  build_runner: ^2.0.5
  flutter_test:
    sdk: flutter
  test: ^1.16.8
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/Logo_short.png"
  min_sdk_android: 21
